## read excel using camline

In [1]:
from pathlib import Path

xlfl = Path.home().joinpath('dat/test/cola.xlsx')
wsnm = ['COCA COLA CO']

In [8]:
import pandas as pd

dp = pd.read_excel(
    xlfl,
    sheet_name=wsnm[0],
    engine='calamine',
    dtype_backend='pyarrow',
    skiprows=3,
    nrows=5,
    skipfooter=0,
    usecols='B:D'
)
dp[:2]

           in million USD  FY '09  FY '10
0  NET OPERATING REVENUES   30990   35119
1      Cost of goods sold   11088   12693

In [12]:
import polars as pl

dl = pl.read_excel(
    xlfl,
    sheet_name=wsnm[0],
    engine='calamine',
    read_options={
        'header_row': 3,
        'skip_rows': 0,
        'n_rows': 5,
        'use_columns': 'B:D',
    },
)

dl[:2]

shape: (2, 3)
┌────────────────────────┬────────┬────────┐
│ in million USD         ┆ FY '09 ┆ FY '10 │
│ ---                    ┆ ---    ┆ ---    │
│ str                    ┆ i64    ┆ i64    │
╞════════════════════════╪════════╪════════╡
│ NET OPERATING REVENUES ┆ 30990  ┆ 35119  │
│ Cost of goods sold     ┆ 11088  ┆ 12693  │
└────────────────────────┴────────┴────────┘

In [6]:
dp.dtypes

Unnamed: 0        string[pyarrow]
in million USD    string[pyarrow]
FY '09            string[pyarrow]
FY '10            string[pyarrow]
FY '11            string[pyarrow]
FY '12            string[pyarrow]
FY '13            string[pyarrow]
FY '14            string[pyarrow]
FY '15            string[pyarrow]
FY '16            string[pyarrow]
FY '17            string[pyarrow]
FY '18            string[pyarrow]
dtype: object