## read excel using camline

In [1]:
from pathlib import Path

xlfl = Path.home().joinpath('dat/test/cola.xlsx')
wsnm = ['COCA COLA CO']

In [5]:
import pandas as pd

dp = pd.read_excel(
    xlfl,
    sheet_name=wsnm[0],
    skiprows=3,
    skipfooter=0,
    engine='calamine',
    dtype_backend='pyarrow',
)
dp[:2]

,Unnamed: 0,in million USD,FY '09,FY '10,FY '11,FY '12,FY '13,FY '14,FY '15,FY '16,FY '17,FY '18
0,<NA>,NET OPERATING REVENUES,30990,35119,46542,48017,46854,45998,44294,41863,35410,31856
1,<NA>,Cost of goods sold,11088,12693,18215,19053,18421,17889,17482,16465,13255,11770

In [3]:
import polars as pl

dl = pl.read_excel(
    xlfl,
    sheet_name=wsnm[0],
    read_options={'header_row': 3},
    engine='calamine',
)

dl[:2]

shape: (2, 12)
┌──────────────┬────────────────────────┬────────┬────────┬───┬────────┬────────┬────────┬────────┐
│ __UNNAMED__0 ┆ in million USD         ┆ FY '09 ┆ FY '10 ┆ … ┆ FY '15 ┆ FY '16 ┆ FY '17 ┆ FY '18 │
│ ---          ┆ ---                    ┆ ---    ┆ ---    ┆   ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str          ┆ str                    ┆ str    ┆ str    ┆   ┆ str    ┆ str    ┆ str    ┆ str    │
╞══════════════╪════════════════════════╪════════╪════════╪═══╪════════╪════════╪════════╪════════╡
│ null         ┆ NET OPERATING REVENUES ┆ 30990  ┆ 35119  ┆ … ┆ 44294  ┆ 41863  ┆ 35410  ┆ 31856  │
│ null         ┆ Cost of goods sold     ┆ 11088  ┆ 12693  ┆ … ┆ 17482  ┆ 16465  ┆ 13255  ┆ 11770  │
└──────────────┴────────────────────────┴────────┴────────┴───┴────────┴────────┴────────┴────────┘

In [6]:
dp.dtypes

Unnamed: 0        string[pyarrow]
in million USD    string[pyarrow]
FY '09            string[pyarrow]
FY '10            string[pyarrow]
FY '11            string[pyarrow]
FY '12            string[pyarrow]
FY '13            string[pyarrow]
FY '14            string[pyarrow]
FY '15            string[pyarrow]
FY '16            string[pyarrow]
FY '17            string[pyarrow]
FY '18            string[pyarrow]
dtype: object