## read excel using camline

In [1]:
from pathlib import Path

xlfl = Path.home().joinpath('dat/test/cola.xlsx')
wsnm = ['COCA COLA CO']

In [8]:
import pandas as pd

dp = pd.read_excel(
    xlfl,
    sheet_name=wsnm[0],
    engine='calamine',
    dtype_backend='pyarrow',
    skiprows=3,
    nrows=5,
    skipfooter=0,
    usecols='B:D'
)
dp[:2]

           in million USD  FY '09  FY '10
0  NET OPERATING REVENUES   30990   35119
1      Cost of goods sold   11088   12693

In [14]:
import polars as pl

dl = pl.read_excel(
    xlfl,
    sheet_name=wsnm[0],
    engine='calamine',
    read_options={
        'column_names': ['usd', 'fy09', 'fy10'],
        'header_row': 3,
        'skip_rows': 0,
        'n_rows': 5,
        'use_columns': 'B:D',
    },
)

dl[:2]

shape: (2, 3)
┌────────────────────────┬────────┬────────┐
│ usd                    ┆ fy09   ┆ fy10   │
│ ---                    ┆ ---    ┆ ---    │
│ str                    ┆ str    ┆ str    │
╞════════════════════════╪════════╪════════╡
│ in million USD         ┆ FY '09 ┆ FY '10 │
│ NET OPERATING REVENUES ┆ 30990  ┆ 35119  │
└────────────────────────┴────────┴────────┘

In [13]:
dp.dtypes

in million USD    string[pyarrow]
FY '09             int64[pyarrow]
FY '10             int64[pyarrow]
dtype: object